---
title: "Estimation s502 project"
author: 
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Methodology 

## Insurance Contracts

Insurance contracts have coverage modifications that need to be considered when modeling the underlying loss variable. Usually, the coverage modifications such as deductibles, policy limits, and coinsurance are introduced as loss control strategies so that unfavorable policyholder behavioral effects can be minimized. There are also situations when certain features of the contract emerge naturally (e.g., the value of insured property in general insurance is a natural upper policy limit). Here we describe two common transformations of the loss variable along with the corresponding probability distribution/mass functions. 

## Truncation 
Incomplete data in the form of truncation occurs when an observation is not recorded due to that observation being below or above a certain threshold. In practice these are referred to as left truncation and right truncation respectively. A common example of left truncation that arises in practice when working with insurance data is with ordinary insurance deductibles.  

### Left Truncation
An observation is left truncated at d if it is not recorded when less than or equal to  d and recorded at the observed value if the observation is greater than $d$. Let $X$ be a random variable representing the size of loss and $L$ be a random variable representing the recorded value. Mathematically, left truncation would be represented as:

$$
L =
\begin{cases}
\text{not recorded} &:x \leq d\\
x &:x> d
\end{cases}
$$
There are a variety of ways that insurance deductibles operate, but with ordinary insurance deductibles there is no incentive for policyholders to report losses less than the deductible amount to the insurance company.  In this situation, the insurer’s data is left truncated for these losses which would be paid by the policyholder and not recorded in the insurer’s data systems. 

## Censoring
Incomplete data in the form of censoring occurs when the observation is recorded at a fixed value if it is below or above a certain threshold. In practice this is referred to as left censoring and right censoring respectively. The right censoring situation arises frequently when working with policy limits in insurance data. 

### Right Censoring
An observation is right censored at u if it is recorded at its observed value if less than u and recorded at u if the observed value is greater than or equal to u. Let X be a random variable representing the size of loss and L be a random variable representing the recorded value. Mathematically, right censoring would be represented as:

$$
L =
\begin{cases}
x &:x < u\\
u &:x\geq u
\end{cases}
$$
It is common for an insurance policy to have a limit which is the maximum amount that the insurer will pay under the terms of the insurance agreement. In situations where the actual damages exceed the limits of the policy, the payment from the insurer will be limited to the policy limit and the loss will be considered right censored.\ 

The derivation of the estimator for the parameter through the maximum likelihood approach. 

- Likelihood function 

\begin{align*}
 L(\theta) &= \prod_{i=1}^{n}\frac{\frac{1}{\theta}e^{-x_i/\theta}}{e^{-d_i/\theta}}\cdot \prod_{i=n+1}^{n+c}\frac{e^{-x_i/\theta}}{e^{-d_i/\theta}} \\
 &= \prod_{i=1}^{n}{\frac{1}{\theta}e^{-(x_i-d_i)/\theta}}\cdot \prod_{i=n+1}^{n+c}{e^{-(x_i-d_i)/\theta}} \\
 &= \frac{1}{\theta^n}e^{-\sum_{i=1}^{n+c}(x_i-d_i)/\theta}
\end{align*}

- The log-likelihood and derivative

\begin{align*}
 \ell(\theta) & = -n\ln\theta- \frac{\sum_{i=1}^{n+c}(x_i - d_i)}{\theta}\\
 \ell'(\theta) & = -\frac{n}{\theta}+ \frac{\sum_{i=1}^{n+c}(x_i - d_i)}{\theta^2} = 0
\end{align*}

- The estimator 
$$\hat{\theta} = \frac{\sum_{i=1}^{n+c}(x_i - d_i)}{n}$$